name: Triggers Events 

on:
  push: 
    branches:
      - "main" 
      - "test-actions"
  pull_request:
    types:
      - opened 
      - reopened 
      - synchronize
    paths:
      - '.github/**'
      - 'README.md'
  
  schedule:
    - cron: "0 0 * * *" # Midnight 
  
  workflow_dispatch:
    
jobs:
  echo-event:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== $GITHUB_EVENT_NAME payload ==="
          cat "$GITHUB_EVENT_PATH"
